### ISSUE TITLE
Support Storybook v6

### ISSUE THREAD

**Issue by andreruffert** [spring-media/storybook-addon-image-snapshots#14]
Is it planned to add support for storybook v6?
I guess this is currently not possible because of [internal storybook v5 dependencies](https://github.com/spring-media/storybook-addon-image-snapshots/blob/master/package.json#L56-L60).

https://storybook.js.org/blog/storybook-6-migration-guide/

**Comment by preventdefault** [comment]
Hey,
not really planned, but it would be great if you can add support for Storybook 6. Maybe it is sufficient enough to add a version range for each Storybook dependency.
